# Generated by Django 3.2.7 on 2021-10-05 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_edu', '0002_cart_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='badge',
            field=models.CharField(max_length=70, verbose_name='For live class or offline'),
        ),
    ]
