# Generated by Django 3.2.7 on 2021-10-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_edu', '0003_alter_post_badge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='emi_start_price',
            field=models.IntegerField(null=True),
        ),
    ]
