# Generated by Django 3.2.7 on 2021-10-06 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_edu', '0005_alter_post_subcategory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subcat', to='app_edu.subcat'),
        ),
        migrations.AlterField(
            model_name='subcat',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Select Only Sub Category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Subcat', to='app_edu.category'),
        ),
    ]
