# Generated by Django 3.2.7 on 2021-10-06 08:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_edu', '0006_auto_20211006_0758'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='City',
            new_name='city',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Company',
            new_name='company',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Country',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='State',
            new_name='state',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Telephone',
            new_name='telephone',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='Zip_Code',
            new_name='zip_code',
        ),
    ]
